//! Behavioural tests for the GV4 group-varint codec in encode.zig.
//!
//! Two kinds of coverage, deliberately kept separate: round-tripping (which
//! only proves this encoder and this decoder agree with each other) and
//! decoding buffers this file did NOT produce — generated once by compiling
//! and running ozz's own `group_varint.cc` against a fixed input, with the
//! resulting bytes pasted in below — which pins the wire format itself.

const std = @import("std");
const zozz = @import("zozz.zig");
const encode = zozz.encode;

test "encodeGV4 / decodeGV4 round-trip across the byte-length boundaries" {
    const cases = [_][4]u32{
        .{ 0, 0, 0, 0 },
        .{ 1, 255, 256, 65535 },
        .{ 65536, 16777215, 16777216, 0xffffffff },
        .{ 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff },
    };
    for (cases) |values| {
        var buf: [17]u8 = undefined;
        const used = try encode.encodeGV4(values, &buf);
        try std.testing.expect(used >= 5 and used <= 17);

        var out: [4]u32 = undefined;
        const consumed = try encode.decodeGV4(buf[0..used], &out);
        try std.testing.expectEqual(used, consumed);
        try std.testing.expectEqualSlices(u32, &values, &out);
    }
}

test "encodeGV4 rejects a buffer shorter than the fixed 17-byte worst case" {
    var buf: [16]u8 = undefined;
    try std.testing.expectError(zozz.Error.BufferTooSmall, encode.encodeGV4(.{ 1, 2, 3, 4 }, &buf));
}

test "decodeGV4 rejects a buffer shorter than the 5-byte minimum" {
    var out: [4]u32 = undefined;
    var buf: [4]u8 = undefined;
    try std.testing.expectError(zozz.Error.BufferTooSmall, encode.decodeGV4(&buf, &out));
}

test "computeGV4WorstBufferSize: 15 bytes per group of 4, plus the header byte" {
    try std.testing.expectEqual(@as(usize, 0), try encode.computeGV4WorstBufferSize(0));
    try std.testing.expectEqual(@as(usize, 17), try encode.computeGV4WorstBufferSize(4));
    try std.testing.expectEqual(@as(usize, 34), try encode.computeGV4WorstBufferSize(8));
}

test "computeGV4WorstBufferSize rejects a count that is not a multiple of 4" {
    try std.testing.expectError(zozz.Error.InvalidArgument, encode.computeGV4WorstBufferSize(5));
}

test "encodeGV4Stream / decodeGV4Stream round-trip an arbitrary-length stream" {
    const values = [_]u32{ 0, 1, 200, 70000, 16777216, 42, 0xffffffff, 3, 9, 99, 999, 9999 };
    const worst = try encode.computeGV4WorstBufferSize(values.len);
    var buf: [64]u8 = undefined;
    try std.testing.expect(worst <= buf.len);

    const used = try encode.encodeGV4Stream(&values, buf[0..worst]);
    try std.testing.expect(used <= worst);

    var out: [values.len]u32 = undefined;
    const consumed = try encode.decodeGV4Stream(buf[0..used], &out);
    try std.testing.expectEqual(used, consumed);
    try std.testing.expectEqualSlices(u32, &values, &out);
}

test "encodeGV4Stream rejects a count that is not a multiple of 4" {
    var buf: [64]u8 = undefined;
    try std.testing.expectError(zozz.Error.InvalidArgument, encode.encodeGV4Stream(&.{ 1, 2, 3 }, &buf));
}

test "decodeGV4Stream rejects a buffer shorter than the minimum encoding" {
    var out: [4]u32 = undefined;
    var buf: [4]u8 = undefined;
    try std.testing.expectError(zozz.Error.BufferTooSmall, encode.decodeGV4Stream(&buf, &out));
}

// Wire-format pin: bytes ozz's own EncodeGV4/EncodeGV4Stream produced, not
// bytes this file's own encoder produced. Generated by compiling
// libs/ozz/src/base/encode/group_varint.cc with a throwaway `main()` that
// called ozz::EncodeGV4 and ozz::EncodeGV4Stream directly on the inputs below
// and printed the result; nothing in zozz.encode was involved in producing
// these bytes.

test "decodeGV4 decodes a buffer ozz's own EncodeGV4 produced" {
    // Input {1, 0x1234, 0x123456, 0xdeadbeef}: one value needing each of the
    // four possible byte lengths (1, 2, 3, 4), so the prefix byte exercises
    // every 2-bit tag value at once.
    const buf = [_]u8{
        0xE4, // prefix: tags (1, 2, 3, 4) bytes for (a, b, c, d)
        0x01, // a = 1 (1 byte)
        0x34, 0x12, // b = 0x1234 (2 bytes, little-endian)
        0x56, 0x34, 0x12, // c = 0x123456 (3 bytes, little-endian)
        0xEF, 0xBE, 0xAD, 0xDE, // d = 0xdeadbeef (4 bytes, little-endian)
    };
    var out: [4]u32 = undefined;
    const consumed = try encode.decodeGV4(&buf, &out);
    try std.testing.expectEqual(@as(usize, buf.len), consumed);
    try std.testing.expectEqualSlices(u32, &.{ 1, 0x1234, 0x123456, 0xdeadbeef }, &out);
}

test "decodeGV4Stream decodes a buffer ozz's own EncodeGV4Stream produced" {
    // Two groups: {0, 1, 200, 70000} then {16777216, 42, 0xffffffff, 3}.
    const buf = [_]u8{
        0x80, 0x00, 0x01, 0xC8, 0x70, 0x11, 0x01, // group 1
        0x33, 0x00, 0x00, 0x00, 0x01, 0x2A, 0xFF, 0xFF, 0xFF, 0xFF, 0x03, // group 2
    };
    var out: [8]u32 = undefined;
    const consumed = try encode.decodeGV4Stream(&buf, &out);
    try std.testing.expectEqual(@as(usize, buf.len), consumed);
    try std.testing.expectEqualSlices(u32, &.{ 0, 1, 200, 70000, 16777216, 42, 0xffffffff, 3 }, &out);
}
